"""empty message

Revision ID: 1f59ca56b8c8
Revises: 581aceceb5d5
Create Date: 2026-04-03 19:17:20.247791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f59ca56b8c8'
down_revision = '581aceceb5d5'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE artikel SET preis = ROUND(preis * 100)")
    op.execute("UPDATE buchung SET preis_pro_einheit = ROUND(preis_pro_einheit * 100)")
    op.execute("UPDATE buchung SET gesamtpreis = ROUND(gesamtpreis * 100)")
    op.execute("UPDATE mitglied SET guthaben = ROUND(guthaben * 100)")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.alter_column('preis',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('buchung', schema=None) as batch_op:
        batch_op.alter_column('preis_pro_einheit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('gesamtpreis',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('mitglied', schema=None) as batch_op:
        batch_op.alter_column('guthaben',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mitglied', schema=None) as batch_op:
        batch_op.alter_column('guthaben',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('buchung', schema=None) as batch_op:
        batch_op.alter_column('gesamtpreis',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('preis_pro_einheit',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.alter_column('preis',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.execute("UPDATE artikel SET preis = preis / 100.0")
    op.execute("UPDATE buchung SET preis_pro_einheit = preis_pro_einheit / 100.0")
    op.execute("UPDATE buchung SET gesamtpreis = gesamtpreis / 100.0")
    op.execute("UPDATE mitglied SET guthaben = guthaben / 100.0")

    # ### end Alembic commands ###
