"""empty message

Revision ID: 385eaa1a2172
Revises: aece232edc17
Create Date: 2026-03-31 18:05:02.808874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385eaa1a2172'
down_revision = 'aece232edc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aussendung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('frequenz', sa.String(length=50), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aussendung')
    # ### end Alembic commands ###
