"""empty message

Revision ID: 4e85cb2d69cc
Revises: 
Create Date: 2025-10-15 17:18:47.520401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e85cb2d69cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artikel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('preis', sa.Float(), nullable=False),
    sa.Column('bestand', sa.Integer(), nullable=False),
    sa.Column('mindestbestand', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bericht',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sql', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mitglied',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('nickname', sa.String(length=10), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('guthaben', sa.Float(), nullable=True),
    sa.Column('blacklist', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('buchung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('artikel_id', sa.Integer(), nullable=True),
    sa.Column('menge', sa.Integer(), nullable=False),
    sa.Column('preis_pro_einheit', sa.Float(), nullable=False),
    sa.Column('gesamtpreis', sa.Float(), nullable=False),
    sa.Column('zeitstempel', sa.DateTime(), nullable=False),
    sa.Column('storniert', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglied.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buchung')
    op.drop_table('user')
    op.drop_table('mitglied')
    op.drop_table('bericht')
    op.drop_table('artikel')
    # ### end Alembic commands ###
