"""empty message

Revision ID: 581aceceb5d5
Revises: 385eaa1a2172
Create Date: 2026-03-31 20:09:41.113878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581aceceb5d5'
down_revision = '385eaa1a2172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aussendung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_days', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aussendung', schema=None) as batch_op:
        batch_op.drop_column('member_days')

    # ### end Alembic commands ###
