"""empty message

Revision ID: 6b86097926f6
Revises: 7906e1e0673b
Create Date: 2026-05-10 12:35:30.013453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b86097926f6'
down_revision = '7906e1e0673b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abrechnung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('zeitstempel', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buchung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abrechnungs_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'abrechnung', ['abrechnungs_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buchung', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('abrechnungs_id')

    op.drop_table('abrechnung')
    # ### end Alembic commands ###
