"""empty message

Revision ID: 7906e1e0673b
Revises: 938e1a5fbb17
Create Date: 2026-05-09 21:37:48.646570

"""
from alembic import op
import sqlalchemy as sa
from config import MINDEST_GUTHABEN


# revision identifiers, used by Alembic.
revision = '7906e1e0673b'
down_revision = '938e1a5fbb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.alter_column('reihenfolge',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('mitglied', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aktiv', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('verborgen', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('schwaerzungs_grenze', sa.Integer(), nullable=True,
                                      server_default=str(MINDEST_GUTHABEN) if MINDEST_GUTHABEN else None))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mitglied', schema=None) as batch_op:
        batch_op.drop_column('verborgen')
        batch_op.drop_column('schwaerzungs_grenze')
        batch_op.drop_column('aktiv')

    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.alter_column('reihenfolge',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
