"""empty message

Revision ID: 938e1a5fbb17
Revises: 1f59ca56b8c8
Create Date: 2026-05-09 19:31:28.418827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938e1a5fbb17'
down_revision = '1f59ca56b8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('mindestbestand')
        batch_op.drop_column('bestand')

    with op.batch_alter_table('buchung', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beschreibung', sa.Text(), nullable=True))

    with op.batch_alter_table('mitglied', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mitglied_email_key'), type_='unique')
    op.add_column(
        "artikel",
        sa.Column(
            "aktiv",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    op.execute(
        """
        UPDATE artikel
        SET "order" = 0
        WHERE "order" is NULL
        """
    )
    op.alter_column('artikel', 'order', new_column_name='reihenfolge', existing_nullable=True, 
                    nullable=False)

    # Sicherheitshalber bestehende NULL-Werte fixen
    op.execute(
        """
        UPDATE artikel
        SET aktiv = TRUE
        WHERE aktiv IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artikel', schema=None) as batch_op:
        batch_op.alter_column('reihenfolge', new_column_name='order',
                              existing_nullable=False, nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('aktiv')
    with op.batch_alter_table('mitglied', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('mitglied_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('buchung', schema=None) as batch_op:
        batch_op.drop_column('beschreibung')

    op.add_column('artikel', sa.Column('bestand', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))
    op.add_column('artikel', sa.Column('mindestbestand', sa.INTEGER(), autoincrement=False, nullable=False, server_default='0'))

    # ### end Alembic commands ###
