"""Final relationship fix and mindestbestand

Revision ID: b5cd8c46b9a3
Revises: 
Create Date: 2025-07-31 21:00:20.224723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5cd8c46b9a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('artikel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('preis', sa.Float(), nullable=False),
    sa.Column('bestand', sa.Integer(), nullable=False),
    sa.Column('mindestbestand', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('mitglied',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pin', sa.String(length=10), nullable=False),
    sa.Column('guthaben', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('pin')
    )
    op.create_table('buchung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('artikel_id', sa.Integer(), nullable=False),
    sa.Column('menge', sa.Integer(), nullable=False),
    sa.Column('preis_pro_einheit', sa.Float(), nullable=False),
    sa.Column('gesamtpreis', sa.Float(), nullable=False),
    sa.Column('zeitstempel', sa.DateTime(), nullable=False),
    sa.Column('storniert', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglied.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaktion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mitglied_id', sa.Integer(), nullable=False),
    sa.Column('artikel_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('menge', sa.Integer(), nullable=False),
    sa.Column('gesamtpreis', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglied.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaktion')
    op.drop_table('buchung')
    op.drop_table('mitglied')
    op.drop_table('artikel')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
