"""Remove Transaktion model, use Buchung for reports

Revision ID: bb144a1ba52d
Revises: b5cd8c46b9a3
Create Date: 2025-08-01 12:02:32.215690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb144a1ba52d'
down_revision = 'b5cd8c46b9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaktion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaktion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mitglied_id', sa.INTEGER(), nullable=False),
    sa.Column('artikel_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('menge', sa.INTEGER(), nullable=False),
    sa.Column('gesamtpreis', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['mitglied_id'], ['mitglied.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
